### ISSUE TITLE
Transcoder - milestone iniziale

### ISSUE THREAD

**Issue by ferraridavide** [ferraridavide/cloud#3]
Il transcoder deve
 - [x] Ricevere correttamente i parametri dalla coda
 - [x] Avviare l'encoding con `ffmpeg` di una singola qualità per processo
 - [x] Comunicare periodicamente il progresso (ogni tot secondi, ogni tot percentuale, al completamento, in caso di errori)
 - [x] Caricare i video encodati su S3 son una struttura definita ([videoId].[qualità].[file_output])
 - [x] Gestire in modo appropriato i file temporanei in locale (consistenza tra inizio e fine job, ripulire le cartelle temporanee prima e dopo)
 - [x] Spostare i parametri di connessione in file .env (assicurarsi che siano configurabili anche su docker compose)
