### ISSUE TITLE
Controller - milestone iniziale

### ISSUE THREAD

**Issue by ferraridavide** [ferraridavide/cloud#4]
- [x] Definire "su carta" gli endpoint necessari e la loro interfaccia
 - [x] [Flusso di upload](https://github.com/ferraridavide/cloud/blob/8312842c28f9d0d05800c1b5fe76c2becc6fc50b/docs/upload-flow.md)
   - [x] Implementare l'avvio di un job di transcoding sulle code
   - [x] #15
